turtlebot3: #namespace
    task_and_robot_environment_name: 'Gmapping-TurtleBot3World-v0'
    ros_ws_abspath: "/root/catkin_ws"
    running_step: 0.0 # amount of time the control will be executed #not used apparently
    pos_step: 0.0    # increment in position for each command # not used apparently
    
    #qlearn parameters
    alpha: 0.1
    gamma: 0.7
    epsilon: 0.9
    epsilon_discount: 0.999
    nepisodes: 10000
    nsteps: 1000

    # model parameters
    algorithm: "PPO" # DQN, PPO, DDQN
    policy_type: "MultiInputPolicy" # MlpPolicy, MultiInputPolicy
    total_timesteps: 500000
    n_steps_before_every_PPO_update: 500
    load_model: False
    continueTraining: False
    saveModel: True   
    use_wandb: True
    use_resnet: True
    config: "DictImageNet5Channel"