turtlebot3: #namespace
    task_and_robot_environment_name: 'TurtleBot3World-v0'
    ros_ws_abspath: "/root/catkin_ws"
    running_step: 0.04 # amount of time the control will be executed
    pos_step: 0.016     # increment in position for each command
    
    #qlearn parameters
    alpha: 0.1
    gamma: 0.7
    epsilon: 0.9
    epsilon_discount: 0.999
    nepisodes: 10000
    nsteps: 1000

    # model parameters
    algorithm: "DQN" # DQN, PPO
    policy_type: "MlpPolicy" # MlpPolicy, MultiInputPolicy
    total_timesteps: 500000
    n_steps_before_every_PPO_update: 500
    load_model: False
    continueTraining: False
    saveModel: True
    use_wandb: True